### ISSUE TITLE
support drawable default hide, show on text not empty

### ISSUE THREAD

**Issue by lvyandev** [MindorksOpenSource/EditDrawableText#4]
e.g:
clear text

**Comment by hi-manshu** [comment]
Can you please elaborate what are you exactly asking for?

**Comment by lvyandev** [comment]
sure, I'd like to know that if the drawable could be invisible at first;
when the EditText content is not empty, the drawable shows with a click event to clear the content

**Comment by hi-manshu** [comment]
This is not there, you can put a pull request with the feature or I will do it in some time.

**Comment by hi-manshu** [comment]
Hey @lvyandev pls check the new release. I have added the requested feature
